apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  labels:
    app: static-site
spec:
  containers:
    - name: static-site
      image: mvmc/mvmc:latest   # the image your pipeline pushes
      ports:
        - containerPort: 80